name: Flutter CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend-*/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend-*/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [frontend-mobile-citoyen, frontend-mobile-agent, frontend-admin-web]

    defaults:
      run:
        working-directory: ./${{ matrix.app }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Linter
      run: flutter analyze

    - name: Run Tests
      run: flutter test || echo "No tests to run"
